# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=500, upload_to='products')),
                ('price', models.FloatField(blank=True, default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('tag', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(0, 'Hết Hàng'), (1, 'Còn Hàng')], default=1)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Catalogue')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
